name: Docker app container testing

on:
  pull_request:
    branches: [develop]

jobs:
  docker:
    name: Check Docker image build
    uses: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if Docker is isntalled
        run: docker --version
      - name: Build app Docker image with Docker
        run: docker build .

  docker-compose:
    name: Test docker-compose build
    uses: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build app Docker image with docker-compose
        run: docker-compose build

  rubocop:
    name: Ruby linter
    uses: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if Docker is isntalled
        run: docker --version
      - name: Build app Docker image with Docker
        run: docker build . -t test-image
      - name: Run tests in container
        run: docker run test-image rubocop --fail-level-error || exit $?
